#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { patchOpenApiDocument } from "./patch-openapi-document.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const repoRoot = path.resolve(__dirname, "..");
const contractsDir = path.join(repoRoot, "contracts", "openapi");
const generatedDir = path.join(repoRoot, "src", "generated", "api");
const patchedContractsDir = path.join(repoRoot, ".tmp", "openapi-patched");

if (!existsSync(contractsDir)) {
  console.error(`Missing contracts directory: ${contractsDir}`);
  process.exit(1);
}

const moduleNames = readdirSync(contractsDir)
  .filter((fileName) => fileName.endsWith(".openapi.json"))
  .map((fileName) => fileName.replace(".openapi.json", ""))
  .sort();

if (moduleNames.length === 0) {
  console.error("No OpenAPI contracts found in contracts/openapi.");
  process.exit(1);
}

function runOpenApiTypeScript(input, output) {
  const packageRoot = path.dirname(require.resolve("openapi-typescript/package.json"));
  const cliPath = path.join(packageRoot, "bin", "cli.js");
  const result = spawnSync(process.execPath, [cliPath, input, "-o", output, "--alphabetize"], {
    cwd: repoRoot,
    stdio: "inherit",
    env: process.env,
  });

  if (result.status !== 0) {
    console.error("openapi-typescript failed.");
    process.exit(result.status ?? 1);
  }
}

function preparePatchedContract(moduleName) {
  const source = path.join(contractsDir, `${moduleName}.openapi.json`);
  const target = path.join(patchedContractsDir, `${moduleName}.openapi.json`);
  const document = patchOpenApiDocument(JSON.parse(readFileSync(source, "utf8")));

  writeFileSync(target, `${JSON.stringify(document, null, 2)}\n`, "utf8");

  return target;
}

if (existsSync(patchedContractsDir)) {
  rmSync(patchedContractsDir, { recursive: true, force: true });
}

mkdirSync(patchedContractsDir, { recursive: true });

for (const moduleName of moduleNames) {
  const input = preparePatchedContract(moduleName);
  const moduleDir = path.join(generatedDir, moduleName);
  const output = path.join(moduleDir, "schema.ts");

  spawnSync("mkdir", ["-p", moduleDir], { stdio: "inherit" });

  runOpenApiTypeScript(input, output);

  writeFileSync(
    path.join(moduleDir, "index.ts"),
    `export type { components, operations, paths } from "./schema";\n`,
    "utf8",
  );
}

const manifest = {
  modules: moduleNames.map((moduleName) => ({
    module: moduleName,
    contract: `contracts/openapi/${moduleName}.openapi.json`,
    schema: `src/generated/api/${moduleName}/schema.ts`,
    pathPrefix: `/api/${moduleName}/v1`,
  })),
};

writeFileSync(path.join(generatedDir, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");

const indexLines = [
  `// Generated by scripts/generate-api.mjs. Do not edit manually.`,
  `export { apiManifest } from "./manifest";`,
  ...moduleNames.map(
    (moduleName) => `export type * as ${toTypeNamespace(moduleName)} from "./${moduleName}";`,
  ),
  "",
];

writeFileSync(path.join(generatedDir, "index.ts"), indexLines.join("\n"), "utf8");

writeFileSync(
  path.join(generatedDir, "manifest.ts"),
  `export const apiManifest = ${JSON.stringify(manifest, null, 2)} as const;\n`,
  "utf8",
);

const readme = readFileSync(path.join(generatedDir, "README.md"), "utf8");
if (!readme.includes("pnpm generate:api")) {
  writeFileSync(
    path.join(generatedDir, "README.md"),
    `${readme.trim()}\n\nRegenerate with \`pnpm generate:api\` after updating \`contracts/openapi\`.\n`,
    "utf8",
  );
}

function toTypeNamespace(moduleName) {
  if (moduleName === "asset") {
    return "AssetApi";
  }

  return `${moduleName[0].toUpperCase()}${moduleName.slice(1)}Api`;
}

console.log(`Generated API types for ${moduleNames.length} modules.`);

rmSync(patchedContractsDir, { recursive: true, force: true });
